export const responseSchemas = {
  error: {
    type: 'object',
    properties: {
      error: {
        type: 'object',
        required: ['code', 'message', 'status', 'requestId'],
        properties: {
          code: { type: 'string' },
          message: { type: 'string' },
          status: { type: 'integer' },
          requestId: { type: 'string' },
          metadata: { type: 'object' },
          stack: { type: 'string' },
        },
      },
    },
  },
  health: {
    type: 'object',
    required: ['status', 'timestamp', 'uptime', 'version', 'environment', 'dependencies'],
    properties: {
      status: { type: 'string', enum: ['ok', 'degraded', 'down'] },
      timestamp: { type: 'string', format: 'date-time' },
      uptime: { type: 'number' },
      version: { type: 'string' },
      environment: { type: 'string' },
      dependencies: {
        type: 'object',
        properties: {
          database: { type: 'string', enum: ['ok', 'down'] },
          redis: { type: 'string', enum: ['ok', 'down'] },
        },
      },
    },
  },
  track: {
    type: 'object',
    required: [
      'id',
      'providerId',
      'provider',
      'title',
      'artist',
      'duration',
      'thumbnail',
      'webUrl',
      'cachedAt',
      'expiresAt',
    ],
    properties: {
      id: { type: 'string', format: 'uuid' },
      providerId: { type: 'string' },
      provider: { type: 'string' },
      title: { type: 'string' },
      artist: { type: 'string' },
      artistId: { type: 'string' },
      album: { type: 'string' },
      albumId: { type: 'string' },
      duration: { type: 'integer', minimum: 0 },
      thumbnail: { type: 'string', format: 'uri' },
      webUrl: { type: 'string', format: 'uri' },
      metadata: { type: 'object' },
      cachedAt: { type: 'string', format: 'date-time' },
      expiresAt: { type: 'string', format: 'date-time' },
    },
  },
  playlist: {
    type: 'object',
    required: [
      'id',
      'providerId',
      'provider',
      'title',
      'creator',
      'trackCount',
      'duration',
      'thumbnail',
      'webUrl',
      'tracks',
      'cachedAt',
      'expiresAt',
    ],
    properties: {
      id: { type: 'string', format: 'uuid' },
      providerId: { type: 'string' },
      provider: { type: 'string' },
      title: { type: 'string' },
      description: { type: 'string' },
      creator: { type: 'string' },
      creatorId: { type: 'string' },
      trackCount: { type: 'integer', minimum: 0 },
      duration: { type: 'integer', minimum: 0 },
      thumbnail: { type: 'string', format: 'uri' },
      webUrl: { type: 'string', format: 'uri' },
      tracks: {
        type: 'array',
        items: { type: 'string', format: 'uuid' },
      },
      metadata: { type: 'object' },
      cachedAt: { type: 'string', format: 'date-time' },
      expiresAt: { type: 'string', format: 'date-time' },
    },
  },
  artist: {
    type: 'object',
    required: [
      'id',
      'providerId',
      'provider',
      'name',
      'thumbnail',
      'webUrl',
      'cachedAt',
      'expiresAt',
    ],
    properties: {
      id: { type: 'string', format: 'uuid' },
      providerId: { type: 'string' },
      provider: { type: 'string' },
      name: { type: 'string' },
      description: { type: 'string' },
      thumbnail: { type: 'string', format: 'uri' },
      subscriberCount: { type: 'integer', minimum: 0 },
      videoCount: { type: 'integer', minimum: 0 },
      webUrl: { type: 'string', format: 'uri' },
      metadata: { type: 'object' },
      cachedAt: { type: 'string', format: 'date-time' },
      expiresAt: { type: 'string', format: 'date-time' },
    },
  },
  searchResult: {
    type: 'object',
    required: ['tracks', 'playlists', 'artists', 'total'],
    properties: {
      tracks: {
        type: 'array',
        items: { $ref: '#/components/schemas/track' },
      },
      playlists: {
        type: 'array',
        items: { $ref: '#/components/schemas/playlist' },
      },
      artists: {
        type: 'array',
        items: { $ref: '#/components/schemas/artist' },
      },
      total: { type: 'integer', minimum: 0 },
    },
  },
  pagination: {
    type: 'object',
    required: ['limit', 'offset', 'total'],
    properties: {
      limit: { type: 'integer' },
      offset: { type: 'integer' },
      total: { type: 'integer' },
    },
  },
  streamInfo: {
    type: 'object',
    required: ['url', 'expiresAt', 'format'],
    properties: {
      url: { type: 'string', format: 'uri' },
      expiresAt: { type: 'string', format: 'date-time' },
      format: { type: 'string' },
      quality: { type: 'string' },
      codec: { type: 'string' },
      bitrate: { type: 'integer' },
    },
  },
} as const;
